### ISSUE TITLE
希望增加评论功能

### ISSUE THREAD

**Issue by gmhl000** [idea-zone/mini-vlook#1]
挺喜欢这个主题的，希望增加评论功能，这个用的挺多的，谢谢。

**Comment by idea-zone** [comment]
OK，回头会加上的。

**Comment by idea-zone** [comment]
> 挺喜欢这个主题的，希望增加评论功能，这个用的挺多的，谢谢。

已添加，上传到集市中，版本是 1.1.0。感谢您的喜欢，哈哈。
