### ISSUE TITLE
配色方案设置

### ISSUE THREAD

**Issue by Fischer0522** [idea-zone/mini-vlook#10]
V2.0.0说提供了新的配色方案，但是在哪里进行设置呢

**Comment by idea-zone** [comment]
> V2.0.0说提供了新的配色方案，但是在哪里进行设置呢

这是文档表述的问题了，新的配色方案，是指和 vlook 和 siyuan 的不同的配色（当前的紫色主题）……
不过，确实有计划添加切换 vlook 自带的 7种配色主题，不过时间可能要晚点……
