### ISSUE TITLE
超级块 的边缘 有异常竖线

### ISSUE THREAD

**Issue by Tlonglan** [idea-zone/mini-vlook#23]
如下图
![image](https://github.com/idea-zone/mini-vlook/assets/38731172/88e9b09e-52b9-40cf-a450-6637202b04d9)

**Comment by idea-zone** [comment]
升级到最新版看看还有这个问题没有。

**Comment by Tlonglan** [comment]
> 升级到最新版看看还有这个问题没有。 ![image](https://user-images.githubusercontent.com/53116704/255461191-391e29ef-5320-4bc3-99a6-8eebb5782972.png)

已经没有这个问题啦
