### ISSUE TITLE
从其他网页剪藏进思源笔记的文件链接，网址有错误显示。

### ISSUE THREAD

**Issue by nefelibata-LY** [idea-zone/mini-vlook#26]
![QQ截图20231223183110](https://github.com/idea-zone/mini-vlook/assets/153592382/6cf0288d-0ed7-49fc-a35e-4dd4a601a913)
说个小问题：从其他网页剪藏进思源笔记的文件链接，网址有错误显示。
这个主题很漂亮，我很喜欢！

**Comment by nefelibata-LY** [comment]
![Uploading QQ截图20231223183110.png…]()

**Comment by idea-zone** [comment]
这个是因为默认情况下， 连续 两个分割线+列表 会被主题识别成列表分栏功能，在最后一个直线后面添加一个新行，如果分割线本身没有意义，直接删除分割线接口。

连续的分割线+ 有序列表/无序列表/引用 都会出现分栏效果。
