### ISSUE TITLE
暗黑模式下代码块背景白色文字也是偏白色，看不清文字

### ISSUE THREAD

**Issue by HDClear** [idea-zone/mini-vlook#29]
感谢大佬提供这么好用的主题，整体效果很喜欢，我喜欢用暗黑模式，碰到了一个问题，代码块的文字看不清，这种情况有什么解决方案吗？

看下效果：
<img width="972" alt="image" src="https://github.com/idea-zone/mini-vlook/assets/14869299/15135f57-e8ec-4756-ba28-f6d44269bdb9">

选中后可以看到文字：
<img width="995" alt="image" src="https://github.com/idea-zone/mini-vlook/assets/14869299/17058538-a126-4d87-a157-bf9ef9c48c6d">

感谢！

**Comment by idea-zone** [comment]
> 感谢大佬提供这么好用的主题，整体效果很喜欢，我喜欢用暗黑模式，碰到了一个问题，代码块的文字看不清，这种情况有什么解决方案吗？
> 
> 看下效果： <img alt="image" width="972" src="https://private-user-images.githubusercontent.com/14869299/312289383-15135f57-e8ec-4756-ba28-f6d44269bdb9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwOTM0OTUsIm5iZiI6MTcxNDA5MzE5NSwicGF0aCI6Ii8xNDg2OTI5OS8zMTIyODkzODMtMTUxMzVmNTctZThlYy00NzU2LWJhMjgtZjZkNDQyNjliZGI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI2VDAwNTk1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY1YjMxZDY3MzVmZjkzMGM2Mjc4Y2Y1Y2NiZDRjNTE1YzJhZTQ1ZjgzMTJkOGViNTI2YWQyMDZlZmFjY2E1ZjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xG9d1u3EXABVYLLlhhVRnEjUyVRso04RmnpjrzZdbkY">
> 
> 选中后可以看到文字： <img alt="image" width="995" src="https://private-user-images.githubusercontent.com/14869299/312289463-17058538-a126-4d87-a157-bf9ef9c48c6d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwOTM0OTUsIm5iZiI6MTcxNDA5MzE5NSwicGF0aCI6Ii8xNDg2OTI5OS8zMTIyODk0NjMtMTcwNTg1MzgtYTEyNi00ZDg3LWExNTctYmY5ZWY5YzQ4YzZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI2VDAwNTk1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIzMjMxYThiYTVkNDdiZWY0MDUxY2Q1YmU1ZWFkNmRmNzYxNTk0NDQ1ODRhZDExNmRhMTdjNDNlMTlkNGEyNTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LxpDHRRE_JdoXrpdx5NcorwuFrcxYbug-CxQofCUbjk">
> 
> 感谢！

抱歉，好久没看 issue 了，这周我会更新一个新版本，解决这个问题。做好会通知你

**Comment by idea-zone** [comment]
问题已经解决，主题更新到 v3.0.10 即可，官方同步拉取可能会存在1~2个小时的延迟。
