### ISSUE TITLE
关于多级标题的显示建议

### ISSUE THREAD

**Issue by zznjobs** [idea-zone/mini-vlook#31]
你好，我是mini-vlook的用户，很喜欢你这个主题，很好看很流畅。
关于多级标题的显示，我向您推荐粉色小屋的设计，真的很清晰明了。
而且不会像自动编号那样经常与本文内容中的编号打架。
![image](https://github.com/idea-zone/mini-vlook/assets/13265176/337a4ab9-1904-4947-9b41-1b12047851fb)

PS：粉色小屋也很好看，但是它在我的电脑上有点卡。

**Comment by yanyu2015** [comment]
是的，我想是否考虑把自动添加标题独立为一个插件呢？这样就可以自由选择是否打开了

**Comment by idea-zone** [comment]
> 是的，我想是否考虑把自动添加标题独立为一个插件呢？这样就可以自由选择是否打开了
通过在文档中添加自定义属性 f=bt 可以关闭。

![image](https://github.com/idea-zone/mini-vlook/assets/53116704/3829d72b-84af-4717-950e-0e6e9d4b7d12)
![image](https://github.com/idea-zone/mini-vlook/assets/53116704/76367209-eacc-4620-9e02-45ea6b1cfed8)
