### ISSUE TITLE
自动编号子标题累加问题

### ISSUE THREAD

**Issue by nuomici2222** [idea-zone/mini-vlook#32]
如图，子标题会累加，不能从头开始
<img width="245" alt="Snipaste_2024-07-26_14-54-00" src="https://github.com/user-attachments/assets/6d070b6a-b764-4ade-8d47-a4a16b97ec17">

**Comment by idea-zone** [comment]
已解决。思源仓库自动更新有延迟，请在 07-29 下午或者第二天更新  mini-vlook 主题到 v3.1.1 以上的版本。

![image](https://github.com/user-attachments/assets/f54df379-51d0-4fe1-a6fe-8de22f284e8d)
![image](https://github.com/user-attachments/assets/e50f306c-44dd-4d76-a0cc-3b09cf06cf5f)

**Comment by nuomici2222** [comment]
感谢，辛苦了🎉
