### ISSUE TITLE
配色

### ISSUE THREAD

**Issue by Tukali** [idea-zone/mini-vlook#4]
原生的vlook有好几种配色，师傅有考虑添加一些其他的配色吗，可以像Dark+的主题那样上面用按键切换，一些比如自动编号功能这种的按钮放在上面，这样就更好了，或者提供自定义css文件的方法，让我们自己去修改也可以

**Comment by idea-zone** [comment]
目前在文档标题的属性块上加上自定义属性 theme，取值为  tm1 到 tm2 是可以实现头图的切换，回头我研究一下，看看可不可以把其他配色也添加上。都放到一个主题其实略大，理论上说，把主题文件夹下的 style/vlook/ 文件夹下面  vlook-v0.css 和 vlook-v1.css 里的值，替换成对应 vlook 主题里面的配色就，可以把 mini-vlook 改成对应主题。vlook-v0.css 对应明亮模式，vlook-v1.css 对应暗模式。你可以尝试一下，回头忙完有时间，我也可能会加（时间不太确定……）
