### ISSUE TITLE
有标题块的文档的显示问题

### ISSUE THREAD

**Issue by xiaoyoucheng** [idea-zone/mini-vlook#6]
带有标题块的文档可以看到如下图所示
会出现横向滚动条，想问下能否自适应屏幕宽度。
![image](https://user-images.githubusercontent.com/33143581/191912534-26aa09b9-9da6-445e-97eb-13aa3e335f97.png)

**Comment by idea-zone** [comment]
![image](https://user-images.githubusercontent.com/53116704/197431036-b69c2ffe-5f0a-4eaa-809e-11d67be96060.png)
在设置里，开这个可以解决。
