### ISSUE TITLE
新建列表时CPU占用100%

### ISSUE THREAD

**Issue by hscui** [idea-zone/mini-vlook#7]
硬件：AMD 3700U+8G内存
系统：WIN10
思源版本：2.2.1
表现：在页面中新建列表时，CPU占用极高，同时基本处于无响应状态

![QQ图片20220927150340](https://user-images.githubusercontent.com/7949195/192456710-2a176aad-9c83-478e-ac95-fd58cb4ed6bf.png)

**Comment by idea-zone** [comment]
现在这个问题还出现吗？

**Comment by hscui** [comment]
> 现在这个问题还出现吗？

我后面又尝试了几次，发现这个问题出现与当前页面本身是否有多个表格或嵌入块有很大关系：表格和嵌入块多，新建表格就容易出现CPU占用问题，空白页面新建就没这个现象。
目前没有使用Mini-vlook主题了。

**Comment by idea-zone** [comment]
> > 现在这个问题还出现吗？
> 
> 我后面又尝试了几次，发现这个问题出现与当前页面本身是否有多个表格或嵌入块有很大关系：表格和嵌入块多，新建表格就容易出现CPU占用问题，空白页面新建就没这个现象。 是因为这个主题在新建表格时需要遍历本页面其他表格吗？ 目前没有使用Mini-vlook主题了。

这个问题已经解决了，是因为我自定义的字数统计功能，被频繁触发，不停的读取整个页面，计算字数，考虑到现在siyuan本身右下角已经有了字数统计功能，把这个功能移除了，现在不卡顿了。在 2.0.1 版本中。
