### ISSUE TITLE
列表变为导图后无法点击设置属性

### ISSUE THREAD

**Issue by hscui** [idea-zone/mini-vlook#8]
给列表增加f=map属性后，鼠标再也无法点击到属性设置那个图标上了：有点像躲迷藏了

![动画](https://user-images.githubusercontent.com/7949195/205287450-ffe57943-380f-47b5-bb68-74a12f3d5b18.gif)

希望能修复这个问题

**Comment by idea-zone** [comment]
> 给列表增加f=map属性后，鼠标再也无法点击到属性设置那个图标上了：有点像躲迷藏了
> 
> ![动画](https://user-images.githubusercontent.com/7949195/205287450-ffe57943-380f-47b5-bb68-74a12f3d5b18.gif) [ ![动画](https://user-images.githubusercontent.com/7949195/205287450-ffe57943-380f-47b5-bb68-74a12f3d5b18.gif) ](https://user-images.githubusercontent.com/7949195/205287450-ffe57943-380f-47b5-bb68-74a12f3d5b18.gif) [ ](https://user-images.githubusercontent.com/7949195/205287450-ffe57943-380f-47b5-bb68-74a12f3d5b18.gif)
> 
> 希望能修复这个问题

已修复，并发布。预计明天或者后天就可以从集市更新。

**Comment by hscui** [comment]
> > 给列表增加f=map属性后，鼠标再也无法点击到属性设置那个图标上了：有点像躲迷藏了
> 
> > 希望能修复这个问题
> 
> 已修复，并发布。预计明天或者后天就可以从集市更新。

我昨天（1月17号）更新了后发现还是原来的问题啊，没有改进。作者自己再试一下？还是我这边用法不对？

另外，昨天更新2.7版了，看群里面截图变化挺大的，不知道适配如何？谢谢。

**Comment by idea-zone** [comment]
> > > 给列表增加f=map属性后，鼠标再也无法点击到属性设置那个图标上了：有点像躲迷藏了
> > 
> > 
> > > 希望能修复这个问题
> > 
> > 
> > 已修复，并发布。预计明天或者后天就可以从集市更新。
> 
> 我昨天（1月17号）更新了后发现还是原来的问题啊，没有改进。作者自己再试一下？还是我这边用法不对？
> 
> 另外，昨天更新2.7版了，看群里面截图变化挺大的，不知道适配如何？谢谢。

现在还有这个问题吗？当前我的是 mini-vlook v2.0.5 版本，思源 2.7.8 版本。适配的化，正常使用感觉问题不大。有bug就反馈，虽然因为 “网速原因” ，平常看 github 频率少一些，但是有留言，看见肯定回复。（一直没有看github消息提示的习惯，哈哈）

![测试map](https://user-images.githubusercontent.com/53116704/223939291-c663a5a6-f269-4ffe-9d84-0e5f3ddd3034.gif)
